name: Deploy Static Site to GitVerse Pages

on:
  push:
    branches:
      - main  # Замените на master, если ваша основная ветка называется так

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Скрипт просто создает папку public и копирует туда всю статику проекта
      - name: Prepare static files
        run: |
          mkdir -p public
          cp -r * public/ 2>/dev/null || true 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'

      - name: Deploy to GitVerse Pages
        id: deployment
        uses: actions/deploy-pages@v2
